name: Build macOS Game App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --windowed --add-data "assets:assets" main.py

      - name: Zip the .app
        run: |
          cd dist
          zip -r YummyTD.zip *.app

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: YummyTD-macOS
          path: dist/YummyTD.zip
